task1/Controllers/InstagramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using task1.Models;

namespace task1.Controllers
{
    public class InstagramController : Controller
    {
        private UsersContext _db;
        private readonly Service service;
        public InstagramController(UsersContext db, Service service)
        {
            _db = db;
            this.service = service;
        }

        public IActionResult MainPage()
        {
            ViewBag.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            User user = _db.ContextUsers.FirstOrDefault(u=>u.Id==id);
            user.Photos = _db.Photos.Where(p => p.UserId == id).ToList();
            return View(user);
        }

        public IActionResult MainPhoto(int id)
        {
            try
            {
                Photo photo = _db.Photos.FirstOrDefault(p => p.Id == id);
                ViewBag.Picture = photo.Picture;
                ViewBag.Likescount = photo.Likescount;
                ViewBag.CommentsCount = photo.Commentscount;
                ViewBag.PictureDescription = photo.PuctureDescription;
                ViewBag.PhotoId = photo.Id;
                ViewBag.Comments = _db.Comments.Where(c => c.PhotoId == id).ToList();
                var user = _db.Users.ToList();
            }catch(NullReferenceException)
            { }
            return View();
        }


        public IActionResult UserSearch(string Person)
        {
            var users = _db.Users.Where(u => u.Login == Person).ToList();
            return View(users);
        }

        public IActionResult MainUser(string id)
        {
            ViewBag.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var user = _db.Users.FirstOrDefault(e => e.Id == id);
            try
            { 
                user.Photos = _db.Photos.Where(p => p.UserId == id).ToList();
            }catch(NullReferenceException)
            {
            }
            return View(user);
        }
        [HttpPost]
        public IActionResult Subscribe(string id)
        {
            int count = 0;
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            User usernow = _db.Users.FirstOrDefault(e => e.Id == userid);
            User userfind = _db.Users.FirstOrDefault(e => e.Id == id);
            foreach (var s in usernow.Subscriptions2)
            {
                if(s==userfind.Id)
                {
                    count++;
                }
            }
            if (count == 0)
            {
                usernow.Subscriptions2.Add(userfind.Id);
                usernow.Subscribers2.Add(usernow.Id);
                userfind.Subscriberscount++;
                usernow.Subscriptionscount++;
                _db.Users.Update(usernow);
                _db.Users.Update(userfind);
            }

            try
            {
                _db.SaveChanges();
            }
            catch(DbUpdateException)
            {

            }

            return Redirect("~/Instagram/MainUser/"+id);
        }

        public IActionResult Subscribers()
        {
            try
            {
                string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                User user = _db.ContextUsers.FirstOrDefault(u => u.Id == id);
                List<User> users = new List<User>();
                foreach (var c in _db.Users.ToList())
                {
                    foreach (var v in user.Subscribers2.ToList())
                    {
                        if (c.Id == v)
                        {
                            users.Add(c);
                        }
                    }
                }
                return View(users);
            }
            catch(ArgumentNullException)
            {
                return RedirectToAction("MainPage");
            }


        }

        public IActionResult Subscriptions()
        {
            try
            {
                string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                User user = _db.ContextUsers.FirstOrDefault(u => u.Id == id);
                List<User> users = new List<User>();
                foreach (var c in _db.Users.ToList())
                {
                    foreach (var v in user.Subscriptions2.ToList())
                    {
                        if (c.Id == v)
                        {
                            users.Add(c);
                        }
                    }
                }


                return View(users);
            }catch(ArgumentNullException)
            {
                return RedirectToAction("MainPage");
            }
        }

        [HttpPost]
        public IActionResult Like(int id)
        {
            Console.WriteLine(id);
            int count = 0;
            try
            {
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            User user = _db.ContextUsers.FirstOrDefault(u => u.Id == userid);
            Photo photo = _db.Photos.FirstOrDefault(p => p.Id == id);
                foreach(var c in photo.UsersLikes.ToList())
                {
                    if(user.Id==c)
                    {

                        count++;
                        Console.WriteLine(count);
                    }
                }
                if(count==0)
                {
                    photo.UsersLikes.Add(user.Id);
                    photo.Likescount++;
                    _db.Photos.Update(photo);
                    _db.SaveChanges();
                }
                return Redirect("~/Instagram/MainPhoto/" + id);
            }
            catch (ArgumentNullException)
            {
                string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                User user = _db.ContextUsers.FirstOrDefault(u => u.Id == userid);
                Photo photo = _db.Photos.FirstOrDefault(p => p.Id == id);
                photo.Likescount++;
                _db.Photos.Update(photo);
                _db.SaveChanges();
                return Redirect("~/Instagram/MainPhoto/" +id);
            }
        }

        public IActionResult SendEmailInfo()
        {
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            service.SendEmailInfo(userid);
            return RedirectToAction("MainPage");
        }

        public IActionResult EditUser()
        {
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            User user = _db.ContextUsers.FirstOrDefault(u => u.Id == userid);
            return View(user);

        }

        [HttpPost]
        public IActionResult EditUser(User user)
        {

            _db.ContextUsers.Update(user);
            //_db.SaveChanges();
            service.SendEmailEdit(user.Id);
            return RedirectToAction("MainPage");
        }


    }

}

task1/Controllers/PhotosController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using task1.Models;

namespace task1.Controllers
{
    public class PhotosController : Controller
    {
        public string mainid;
        private UsersContext _db;

        public PhotosController(UsersContext db)
        {
            _db = db;
        }

        public IActionResult Add(string userid)
        {
            Photo photo = new Photo
            {
                UserId = userid
            };
            
            return View(photo);
        }

        [HttpPost]
        public IActionResult Add(Photo photo)
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            User user = _db.Users.FirstOrDefault(u => u.Id == id);
            if (ModelState.IsValid)
            {
                if (photo != null)
                {
                    Photo p = new Photo
                    {
                        Picture = photo.Picture,
                        PuctureDescription = photo.PuctureDescription,
                        Commentscount = 0,
                        Likescount = 0,
                        UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value
                };
                    user.Photoscount++;
                    _db.Photos.Add(p);
                    _db.SaveChanges();
                    
                }
                return Redirect("~/Instagram/MainPage");
            }
            else
            {
                return View("Add");
            }
        }

        [HttpPost]
        public IActionResult Comment(int id,Comment comment)
        {
            if (ModelState.IsValid)
            {
                if (comment != null)
                {
                    Comment c = new Comment
                    {
                        CommentText=comment.CommentText,
                        PhotoId=id,
                        UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value
                    };
                    Photo photo = _db.Photos.FirstOrDefault(p => p.Id == id);
                    photo.Commentscount++;
                    _db.Comments.Add(c);
                    _db.SaveChanges();

                }
                return Redirect("~/Instagram/MainPhoto/"+id);
            }
            else
            {
                return Redirect("~/Instagram/MainPhoto/"+id);
            }
        }

    }

}

task1/Views/Instagram/EditUser.cshtml
@model task1.Models.User
@{ ViewBag.Title = "Редактировать пользователя";
    Layout = "_Layout"; }
<h2>Заполните форму для редактирования пользователя</h2>
<div class="row">
    <div class="phone_add_form col-md-6">
        <form asp-action="EditUser" method="post">
            <div class="form_row">
                <label for="">
                    Наименование
                    <input asp-for="@Model.Avatar" type="text">
                    <span asp-validation-for="@Model.Avatar"></span>
                </label>
            </div>
            <div class="form_row">
                <label for="">
                    Страна производства
                    <input asp-for="@Model.PhoneNumber" type="text">
                    <span asp-validation-for="@Model.PhoneNumber"></span>
                </label>
            </div>
            <div class="form_row">
                <label for="">
                    Описание
                    <input asp-for="@Model.UserDescription" type="text">
                    <span asp-validation-for="@Model.UserDescription"></span>
                </label>
            </div>
            <button type="submit">Редактировать</button>
        </form>
    </div>
</div>

task1/Views/Instagram/MainPage.cshtml
@model User
@{
    ViewBag.Title = "Мобильные телефоны";
    Layout = "_Layout";
}
<div class="table_section">
    <img src="@Model.Avatar" class="img-thumbnail">
    <h1>@Model.Login</h1>
    <h3>Фотографий:@Model.Photoscount</h3>
    <a asp-action="Subscribers" asp-controller="Instagram"><h3>Подписчиков:@Model.Subscriberscount</h3></a>
    <a asp-action="Subscriptions" asp-controller="Instagram"><h3>Подписок:@Model.Subscriptionscount</h3></a>
    <p>@Model.UserDescription</p>
    <a asp-action="Add" asp-controller="Photos" asp-route-userid="@ViewBag.UserId">Загрузить фото</a><br />
    <a asp-area="" asp-controller="Instagram" asp-action="SendEmailInfo">Отправить информацию об аккаунте на Email</a><br />
    <a asp-action="EditUser">Редактировать</a>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        @foreach (var photo in Model.Photos)
        {
            <div class="col">
                <div class="card">
                    <a asp-action="MainPhoto" asp-route-id="@photo.Id"><img src="@photo.Picture" class="card-img-top" alt="..."></a>
                    <div class="card-body">
                    </div>
                </div>
            </div>
        }
    </div>
</div>

task1/Views/Instagram/MainPhoto.cshtml
@model Comment
@{ ViewBag.Title = "Фото";
                Layout = "_Layout"; }
<div class="col">
    <div class="card">
        <img src="@ViewBag.Picture" class="card-img-top" alt="...">
        <p>@ViewBag.PictureDescription</p>
 <p>"@ViewBag.CommentsCount" Комментариев</p>
        <p>"@ViewBag.Likescount" Отметок Нравится</p>
        @foreach (var comment in @ViewBag.Comments)
        {
    <p>@comment.User.Login:@comment.CommentText</p>}
            @using (Html.BeginForm("Comment", "Photos", new { id = @ViewBag.PhotoId }))
            {
                  <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">Комментировать:</span>
                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" asp-for="@Model.CommentText">
            </div>
    <div class="form-row">
        <label for="">
            <input disabled type="text" value="@User.Identity.Name" hidden>
        </label>
        <input asp-for="@Model.PhotoId" type="hidden" value="@ViewBag.PhotoId" hidden>
    </div>
            <button type="submit">Опубликовать</button>}
         @using (Html.BeginForm("Like", "Instagram", new { id = @ViewBag.PhotoId }))
                {
                    <button type="submit">Like</button>}
            <div class="card-body">
            </div>
    </div>
</div>

task1/Views/Instagram/MainUser.cshtml
@model User
@{ ViewBag.Title = "Пользователь";
    Layout = "_Layout"; }
<div class="table_section">
    <img src="@Model.Avatar" class="img-thumbnail">
    <h1>@Model.Login</h1>
    <h3>Фотографий:@Model.Photoscount</h3>
    <h3>Подписчиков:@Model.Subscriberscount</h3>
    <h3>Подписок:@Model.Subscriptionscount</h3>
    <p>@Model.UserDescription</p>
    <h3>
        @using (Html.BeginForm("Subscribe", "Instagram", new { id = Model.Id }))
        {
<button type="submit">Подписаться</button>}
    </h3>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        @foreach (var photo in Model.Photos)
        {
<div class="col">
    <div class="card">
        <a asp-action="MainPhoto" asp-route-id="@photo.Id"><img src="@photo.Picture" class="card-img-top" alt="..."></a>
        <div class="card-body">
        </div>
    </div>
</div>}
    </div>
</div>

task1/Views/Instagram/Subscribers.cshtml
@model List<User>
@{ ViewBag.Title = "Подписчики";
                Layout = "_Layout"; }
<div>
    @foreach (var user in Model)
    {
<a asp-action="MainUser" asp-controller="Instagram" asp-route-id="@user.Id">
    <p>@user.Login</p>
</a>            }
</div>

task1/Views/Instagram/Subscriptions.cshtml
@model List<User>
@{ ViewBag.Title = "Подписчики";
    Layout = "_Layout"; }
<div>
    @foreach (var user in Model)
    {
<a asp-action="MainUser" asp-controller="Instagram" asp-route-id="@user.Id">
    <p>@user.Login</p>
</a>        }
</div>

task1/Views/Instagram/UserSearch.cshtml
@model List<User>
@{
    ViewBag.Title = "Мобильные телефоны";
    Layout = "_Layout";
}
<div>
    @foreach (var user in Model)
    {
        <a asp-action="MainUser" asp-controller="Instagram" asp-route-id="@user.Id">
            <p>@user.Login</p></a>
            }
    </div>